Add modal link to other advice pages
Energy-Sparks/energy-sparks pull request #2479
Opened 2023-02-24 17:32 UTC by iant

2023-02-27 14:25 UTC, ldodds requested changes
Tables should have a single footnote, so we either combine (where they have different content) or separate them out. Have left comments on how to handle the situations I've flagged up.

2023-02-27 14:25 UTC, ldodds commented on app/views/schools/advice/electricity_long_term/_current_usage.html.erb
> +<%= render 'schools/advice/how_have_we_analysed_your_data_table_caption', data_target: "how-have-we-analysed-your-data-footnotes" %>
This won't look right with 2 separate lines. We need to combine into a single table footnote. Suggest just replacing the existing footnote with the new standard on, and moving the "Review our analysis" to a separate line without the right alignment

2023-02-27 14:25 UTC, ldodds commented on app/views/schools/advice/electricity_recent_changes/_your_recent_electricity_use_table.html.erb
> +<%= render 'schools/advice/how_have_we_analysed_your_data_table_caption', data_target: "how-have-we-analysed-your-data-footnotes" %>
Same as above, need to have a single table footnote with both bits of content.

2023-02-28 08:43 UTC, iant commented
hi @ldodds just pushed some updates addressing your review comments.  I think this is ok for a final review.

2023-02-28 14:03 UTC, ldodds approved these changes

2023-02-28 14:22 UTC, merged