Tidy up admin options on school manage meters page
Energy-Sparks/energy-sparks pull request #2858
Opened 2023-06-22 07:50 UTC by iant

2023-06-22 16:13 UTC, iant commented on app/views/schools/meters/index.html.erb
> -      <%= t('schools.meters.index.data_processing_turned_on_message') %>
:+1:

2023-06-23 07:21 UTC, iant commented
@ldodds default issues admin user partial and data_processing_turned_on_message tooltip added.  I think this one's ready for review again.

2023-06-23 11:26 UTC, ldodds requested changes

2023-06-23 11:26 UTC, ldodds commented on app/views/schools/meters/index.html.erb
> +    <% if can?(:validate_meters, @school) && @school.meters_with_readings.any? && 1==2%>
think you left some debug in here, should be `@school.process_data?`

2023-06-26 08:42 UTC, ldodds approved these changes

2023-06-26 08:42 UTC, merged