Award bonus points for adding photos to activities and actions
Energy-Sparks/energy-sparks pull request #2900
Opened 2023-07-19 15:19 UTC by iant

This PR changes the scoring system for both pupil and adult lead activities so that bonus points are awarded if the school adds one or more photos to the description.  

- [x] Adds a new system wide setting for default bonus points for adding images to activities and actions
- [x] Adds a note to form field to both forms to indicate bonus points
- [x] Revises logic to ensure bonus points are recorded correctly

2023-07-20 14:31 UTC, iant commented
![Screenshot 2023-07-20 at 15 31 04](https://github.com/Energy-Sparks/energy-sparks/assets/25906/22177404-9ff8-4931-b8f8-78f1538568c0)

2023-07-20 14:35 UTC, iant commented
![Screenshot 2023-07-20 at 15 34 40](https://github.com/Energy-Sparks/energy-sparks/assets/25906/4a871ef3-cd9e-4e87-b4f8-f82aeda38ff2)

2023-07-21 08:22 UTC, ldodds requested changes

2023-07-21 08:22 UTC, ldodds commented on app/models/observation.rb
> +  def add_points_for_included_images
This isn't quite right. If a school records an activity or intervention for a previous school year and adds a photo, they'll still get the bonus points for the image. They should only get the bonus if they're actually scoring points. 

So think it needs a check to confirm that the bonus is only added if the score is non zero?

2023-07-21 10:43 UTC, ldodds approved these changes

2023-07-21 11:12 UTC, merged