Create dashboard prompt to complete programme
Energy-Sparks/energy-sparks pull request #3059
Opened 2023-09-15 10:12 UTC by iant

2023-09-26 10:20 UTC, ldodds requested changes

2023-09-26 13:48 UTC, iant commented on app/views/management/schools/_prompt_to_complete_program.html.erb
> +<% if @programmes_to_prompt.present? %>
:+1: done

2023-09-26 13:48 UTC, iant commented on app/views/management/schools/_prompt_to_complete_program.html.erb
> +        status: :positive,
:+1: done

2023-09-27 08:37 UTC, ldodds approved these changes

2023-09-27 08:48 UTC, merged