Electricity use during current holiday
Energy-Sparks/energy-sparks pull request #3448
Opened 2024-02-26 14:28 UTC by tbhi

2024-02-26 14:28 UTC, tbhi commented on db/schema.rb
not sure why this has changed so much

2024-03-01 16:43 UTC, ldodds requested changes

2024-03-01 16:43 UTC, ldodds commented on app/controllers/comparisons/electricity_consumption_during_holiday_controller.rb
> +    def title_key
report key

2024-03-01 16:43 UTC, ldodds commented on app/views/comparisons/electricity_consumption_during_holiday/_introduction.html.erb
Can remove this now

2024-03-05 13:37 UTC, ldodds approved these changes

2024-03-05 15:54 UTC, merged