Change in electricity use between this holiday and the same holiday last year
Energy-Sparks/energy-sparks pull request #3452
Opened 2024-02-28 17:41 UTC by tbhi

2024-03-01 17:14 UTC, ldodds requested changes

2024-03-01 17:14 UTC, ldodds commented on app/views/comparisons/change_in_electricity_holiday_consumption_previous_years_holiday/_introduction.html.erb
as before can remove this and add report key

2024-03-01 17:14 UTC, ldodds commented on app/views/comparisons/change_in_electricity_holiday_consumption_previous_years_holiday/_tables.html.erb
> +          <%= result.name_of_current_period %>
We're going to need to make some changes to the alert class here for `name_of_current_period` and `name_of_previous_period`. These values will be text and we are only storing values that have been generated with locale of English. So Welsh uses will see English period names.

The `period_name` code looks something like:

```
  protected def period_name(period)
    I18nHelper.holiday(period.type)
  end
```

So we'll need to change the alert to declare a variable and add a method that returns the `period.type`. We can then we can use that to display the correct text in the table.

We only need to do this for any text to be displayed. Any constants can be used as is.

2024-03-01 17:19 UTC, ldodds commented on app/views/comparisons/change_in_electricity_holiday_consumption_previous_years_holiday/_tables.html.erb
> +          <%= result.name_of_current_period %>
I've not looked at the values recently. If they can be easily mapped back to existing keys that might be simpler, but if we can fix at source that's probably for the best.

2024-03-05 16:06 UTC, tbhi commented on app/views/comparisons/change_in_electricity_holiday_consumption_previous_years_holiday/_tables.html.erb
> +            <a href="#footnotes">(*1)</a>
makes sense to leave until footnotes are refactored?

2024-03-11 09:18 UTC, ldodds approved these changes

2024-03-11 09:18 UTC, ldodds commented on app/views/comparisons/change_in_electricity_holiday_consumption_previous_years_holiday/_table.html.erb
> +      <%= row.with_var val: result.difference_kwh, unit: :kw %>
`:kwh` I think?

2024-03-11 10:19 UTC, merged